// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package gotik

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createStmt, err = db.PrepareContext(ctx, create); err != nil {
		return nil, fmt.Errorf("error preparing query Create: %c.Writer", err)
	}
	if q.deleteByIdStmt, err = db.PrepareContext(ctx, deleteById); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteById: %c.Writer", err)
	}
	if q.findAllStmt, err = db.PrepareContext(ctx, findAll); err != nil {
		return nil, fmt.Errorf("error preparing query FindAll: %c.Writer", err)
	}
	if q.findByIdStmt, err = db.PrepareContext(ctx, findById); err != nil {
		return nil, fmt.Errorf("error preparing query FindById: %c.Writer", err)
	}
	if q.updateStmt, err = db.PrepareContext(ctx, update); err != nil {
		return nil, fmt.Errorf("error preparing query Update: %c.Writer", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createStmt != nil {
		if cerr := q.createStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStmt: %c.Writer", cerr)
		}
	}
	if q.deleteByIdStmt != nil {
		if cerr := q.deleteByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteByIdStmt: %c.Writer", cerr)
		}
	}
	if q.findAllStmt != nil {
		if cerr := q.findAllStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findAllStmt: %c.Writer", cerr)
		}
	}
	if q.findByIdStmt != nil {
		if cerr := q.findByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findByIdStmt: %c.Writer", cerr)
		}
	}
	if q.updateStmt != nil {
		if cerr := q.updateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStmt: %c.Writer", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db             DBTX
	tx             *sql.Tx
	createStmt     *sql.Stmt
	deleteByIdStmt *sql.Stmt
	findAllStmt    *sql.Stmt
	findByIdStmt   *sql.Stmt
	updateStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:             tx,
		tx:             tx,
		createStmt:     q.createStmt,
		deleteByIdStmt: q.deleteByIdStmt,
		findAllStmt:    q.findAllStmt,
		findByIdStmt:   q.findByIdStmt,
		updateStmt:     q.updateStmt,
	}
}
