// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package gotik

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (User, error)
	DeleteById(ctx context.Context, id int64) error
	FindAll(ctx context.Context) ([]User, error)
	FindById(ctx context.Context, id int64) (User, error)
	Update(ctx context.Context, arg UpdateParams) error
}

var _ Querier = (*Queries)(nil)
